### ISSUE TITLE
To-do project 2

### ISSUE THREAD

**Issue by hannahrwing** [hannahrwing/blossom-algorithm#4]
- [ ] ~~Fix time-thingy~~
- [x] Calculate gradient
- [x] Fix Classic Newton
- [x] Task 12
- [ ] Snygga till kod (remove unnecessary code, make it look neat)
- [x] Comment code
- [x] Rename default
- [x] Tests
- [ ] Fix when guessing correctly
- [ ] Hanna: move norm thing to test file
- [ ] Nils: Fix plot thing to generalise for any interval, fix name
- [ ] William: Fix div 0
- [x] Anton: Comment code
